### PR TITLE
New: vue/html-button-has-type rule

### LINKED ISSUE #894: Button tags require type.
**Please describe what the rule should do:**

All `<button>` tags require the type to be set.
**What category should the rule belong to?**

- [ ] Enforces code style
- [X] Warns about a potential error
- [ ] Suggests an alternate way of doing something
- [ ] Other (please specify:)

**Provide 2-3 code examples that this rule should warn about:**
```vue
<button>Test</button>
<button class="btn btn-danger">Delete</button>
```

**Additional context**

Forgetting the `type` attribute on a button defaults it to being a submit type. This is nearly never what is intended, especially in your average one-page application.

`type="button"` stops the webpage from submitting the form, instead allowing the `@click` handler to work without the page reloading soon after.

`type="submit"` can be used explicitly to allow the default behaviour.

### PR DESCRIPTION
**Pull request by SanterreJo**

### CODE REVIEW

**Comment by SanterreJo** [comment]
This rule fixes #894

**Comment by Etheryte** [comment]
Thanks for putting in the hours to make this work. Can't wait to have it merged, would be insanely helpful on large codebases.

**Comment by miralize** [comment]
This would be great to get into the next version!

**Comment by mrleblanc101** [comment]
Almost a year, will this get merged ?

**Comment by ota-meshi** [comment]
Sorry for not commenting for very long time.

I thought it would be better to implement a rule that checks the required attributes of every element, using something like [component data](https://vuejs.github.io/vetur/guide/component-data.html), rather than creating a `<button>` specific rule, but now I found it difficult to implement this generic rule.

Could you update this PR to resolve the conflict?

**Comment by SanterreJo** [comment]
@ota-meshi
merge conflict is resolved

**Review by ota-meshi — APPROVED** [review]
Thank you!

**Pull request merged**
