### PR TITLE
⭐️New: Add rule `require-component-name`

### PR DESCRIPTION
**Pull request by hirokiosame**
This rule requires components be named

### CODE REVIEW

**Comment by armano2** [comment]
Additionally we should think what should happens with mixins because for now we have 
```
const componentComments = sourceCode.getAllComments().filter(comment => /@vue\/component/g.test(comment.value))
```
and we have no way of telling if something is mixin or component

**Comment by michalsnik** [comment]
Hey, have you looked at the discussion here https://github.com/vuejs/eslint-plugin-vue/issues/265 @hirokiosame ? The PR @chrisvfritz mentioned has been merged and we didn't yet agree whether we want to introduce this rule or not. I'll put on-hold for now and let's continue discussion there, as I have very mixed feelings about it.

**Comment by hirokiosame** [comment]
Ah great thanks guys. Let me know what you guys decide on and I can work on it further.

**Comment by rodrigopedra** [comment]
Can we add an option force the component name to match the file name?

e.g. 

This is **correct:**:

~~~vue
// src/components/MyComponent.vue

<script>
export default {
    name: 'MyComponent',
}
</script>

<template />
~~~

This is **incorrect:**:

~~~vue
// src/components/MyComponent.vue

<script>
export default {
    name: 'MyCompnent', // missed the o
}
</script>

<template />
~~~

It would help to catch cases where someone mistyped the component name.

**Comment by chrisvfritz** [comment]
> If possible I wanted to understand the rationale for not specifying a name property for any component. I always set them for consistency but perhaps it is a bit of over engineering on my side.

@rodrigopedra Great question! 🙂 My reasoning is actually the same as yours: consistency. 😄 When we always use `.vue` files and don't specify a name, we guarantee that the component's name always matches the file name. When you specify the name _again_ in a `name` property, you're not only writing more code unnecessarily, but also forcing yourself to either manually make sure the two names matche (to avoid confusing behavior) or write some kind of tooling to help you avoid mistakes, like you're doing now. 🙂 

> If you can, please review it and I can send a PR

Sounds great. This would be a new rule (maybe `match-component-file-name`), so a new PR would be best. Writing unit tests for the rule will also help us review it, because they'll not only describe the behavior you're trying to create, but if the tests are robust and they pass, we can focus on higher level aspects of the code.

**Comment by rodrigopedra** [comment]
@chrisvfritz thank you very much for the feedback, I will try to send a PR later this week.

**Comment by rodrigopedra** [comment]
Hi @hirokiosame , check the work that was done #668 , it was initially based in your code in this PR, and we defaulted to `jsx` and added options to other file extensions.

**Comment by chrisvfritz** [comment]
@michalsnik I think this can be closed unless someone objects.

**Pull request closed without merging**
