### PR TITLE
fix: replace typeParameters with typeArguments

### PR DESCRIPTION
**Pull request by KaelWD**
https://github.com/typescript-eslint/typescript-eslint/pull/5384

#2256 missed a few

### CODE REVIEW

**Review by FloEdelmann — APPROVED** [review]
Thanks! Looks good from my side. I think we should release this as a patch version as soon as possible.

**Review by ota-meshi — APPROVED** [review]
Thank you! I didn't notice it.

**Comment by ota-meshi** [comment]
I looked into why the test is not currently failing. It appears that the deprecated typeParameters property is still left as an alias on those nodes. Therefore, there is no need to rush patch releases.
However, I haven't released this plugin recently, so I would like to check the remaining PRs and recent issues and release it soon.

**Comment by KaelWD** [comment]
It floods the terminal with depreciation notices in my project, idk why it doesn't here.

**Comment by ota-meshi** [comment]
Isn't that a warning about ESLint v9? If so, we support the old ESLint and cannot simply replace it. I have a number of plugins that have similar issues, so I'm considering whether to create a util package for them.

**Comment by KaelWD** [comment]
No it's from typescript-eslint 6

**Comment by ota-meshi** [comment]
Oh really. I've never seen it so I don't know.

**Pull request merged**
