### PR TITLE
[Update] Make `vue/attributes-order` fixable

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR makes `vue/attributes-order` fixable. #401
In case of `Attribute "A" should go before  "B"` error message, autofix will move A before B

### CODE REVIEW

**Comment by ota-meshi** [comment]
@michalsnik
Thank you for review!
I added a test case that your requested.
Please check again it.

https://github.com/vuejs/eslint-plugin-vue/pull/405/commits/dbb945dfad5278425fe2b31dd9a47cf100b975ce

**Comment by jeremyzahner** [comment]
@ota-meshi @michalsnik Just applied this branch to a codebase with more than 400 attributes-order errors and it worked smoothly.

**Comment by michalsnik** [comment]
Music to my ears! Thank you @ota-meshi awesome work :)

**Comment by michalsnik** [comment]
Sorry guys I took soo long... But I just released v4.5.0, enjoy! :)

**Pull request merged**
