### PR TITLE
New rule: external-script

### PR DESCRIPTION
**Pull request by piehei**
This adds a new rule based on the discussion in #192.

This is my first PR to the project so I will delay PRs for external-style and external-template until this one is shown green light or issues are pointed out :)

### CODE REVIEW

**Comment by michalsnik** [comment]
Hey @piehei, thanks for submitting the PR. Please make sure your code doesn't have any linting issues and all tests are passing. Then we'll perform Code Review :)

**Comment by piehei** [comment]
@michalsnik thanks :) It passes now. I'm still mostly sure that something has to be changed and it's not yet completely ready for merge.

**Comment by piehei** [comment]
I found a couple of bugs. I'll fix them and update this after that.

**Comment by piehei** [comment]
Added error line reporting.

**Comment by michalsnik** [comment]
Thanks @piehei 👍 However we're in the middle or preparing official v4 release, so it's going to be on hold until then. I hope you understand :)

**Comment by piehei** [comment]
@michalsnik - yes, of course! I'm in no hurry. Only plan is to contribute something useful and get to know the process :-)

**Comment by michalsnik** [comment]
Sorry @piehei , but we're not going to merge this rule. We're going to focus more on rules aligned with official style guide and force good practices. If you'd like to help, please take a look at propositions labeled `Accepted Proposition`, they're ready to work on :)

**Pull request closed without merging**
