### PR TITLE
Rename `vue/no-invalid-attribute-name` rule to `vue/invalid-attribute-name` and add it to presets

### PR DESCRIPTION
**Pull request by ota-meshi**

### CODE REVIEW

**Review by FloEdelmann — APPROVED** [review]

**Comment by FloEdelmann** [comment]
Maybe before we release v9, should we rename `no-invalid-attribute-name` to `valid-attribute-name` for consistency?

**Comment by ota-meshi** [comment]
I think it's a good idea to rename the rule. I will rename in this PR.

**Review by FloEdelmann — APPROVED** [review]

**Comment by ota-meshi** [comment]
Thank you for checking! I will release v9 tomorrow if I have time.

**Comment by FloEdelmann** [comment]
I already updated the changelog draft in [#1850](https://togithub.com/vuejs/eslint-plugin-vue/issues/1850), so releasing should be as straightforward as possible.

**Comment by FloEdelmann** [comment]
@ota-meshi The documentation for this rule is not yet published. Maybe the npm cache needs to be cleared for the production build, too?

https://eslint.vuejs.org/rules/valid-attribute-name.html

**Comment by ota-meshi** [comment]
Thank you for letting me know. I cleared the cache and redeployed.

**Pull request merged**
