### PR TITLE
⭐️New: Add `vue/component-tags-order` rule

### LINKED ISSUE #140: Rule Proposal: `vue/component-tags-order`
**Please describe what the rule should do:**

This rule warns about the order of the script, template & style tags.

**What category of rule is this? (place an "X" next to just one item)**

`[x]` Enforces code style
`[ ]` Warns about a potential error
`[ ]` Suggests an alternate way of doing something
`[ ]` Other (please specify:)

**Provide 2-3 code examples that this rule will warn about:**

vue/component-tags-order: ["warning", order: [ "script", "template", "style" ] ];

```
<template></template>
<script></script>
<style></style>
```
However, the following should be considered fine:

```
<script></script>
<template></template>
<style></style>
```

### PR DESCRIPTION
**Pull request by ota-meshi**
Close #140

### CODE REVIEW

**Comment by armano2** [comment]
this is not going to work if `<template></template>` is not present in file
there are 2 valid solutions for it
- fix it (if possible)
- add not to documentation about this

**Comment by derek-knox** [comment]
@ota-meshi Any status update on this? It is starting to look stale.

**Comment by ota-meshi** [comment]
@derek-knox 

Hello!

> this is not going to work if `<template></template>` is not present in file

I'm open PR to the `vue-eslint-parser` to solve this problem.

**Comment by ota-meshi** [comment]
I changed this to work even if `<template></template>` is not present in file.

**Pull request merged**
