### PR TITLE
#65 - vue/no-invalid-v-for shouldn't catch slots

### PR DESCRIPTION
**Pull request by armano2**
#65

### CODE REVIEW

**Comment by armano2** [comment]
I think we should add few additional internal vue elements like `<router-view>` `<transition>` `<transition-group>`

**Comment by mysticatea** [comment]
Thank you for contributing!

Oh, [the `lib/html-elements.json`](https://github.com/vuejs/eslint-plugin-vue/blob/9fce35dba3883cf8c564eb18693c3882e71d21c9/lib/utils/html-elements.json) seems wrong. [The `<slot>` elements are valid HTML elements](https://html.spec.whatwg.org/#the-slot-element). Could you replace `content`, `shadow`, and `element` (those were dropped from standard) by `slot` in the `lib/html-elements.json`?

> I think we should add few additional internal vue elements like <router-view> <transition> <transition-group> but they should be not allowed?

Those are embedded custom components. I believe that embedded custom components also need `key` attributes in iterations.

image

**Comment by armano2** [comment]
I found out that there is few more missing html5 valid tags:
`slot`, `blockquote`, `iframe`, `noframes`, `picture`, `tfoot`

**Comment by armano2** [comment]
base on https://github.com/vuejs/vue/blob/dev/src/platforms/web/util/element.js `content`, `shadow`, and `element` can be still in use

**Pull request merged**
