### PR TITLE
⭐️html-indent: Add "smart-tab" indent type (fixes #426)

### LINKED ISSUE #426: html-indent: Please support smart-tabs
**Tell us about your environment**

* **ESLint Version:** 4.18.2
* **eslint-plugin-vue Version:** 4.3.0
* **Node Version:** 9.5.0

**Please show your full configuration:**

```js
module.exports = {
	root: true,
	plugins: ["vue"],
	extends: [
		"eslint:recommended",
		"plugin:vue/recommended",
	],
	rules: {
		"no-mixed-spaces-and-tabs" : ["error", "smart-tabs"],
		"vue/html-indent": ["error", "tab", {"alignAttributesVertically": true}],
		"vue/max-attributes-per-line": ["error", {
			"multiline": {
				"allowFirstLine": true,
			},
		}],

	},
};
```

**What did you do? Please include the actual source code causing the issue.**

```vue
<template>
	<img src="/example.png"
	     alt="Sample Image">
</template>
<script>
	export default {
	};
</script>
```
With tabs/spaces made explicit:
```vue
<template>
»	<img·src="/example.png"
»	·····alt="Sample·Image">
</template>
<script>
»	export·default·{
»	};
</script>
```

**What did you expect to happen?**

Should not raise html-indent error.

**What actually happened? Please include the actual, raw output from ESLint.**

```
$ /home/lukeshu/t/node_modules/.bin/eslint component.vue

/home/lukeshu/t/component.vue
  3:2  error  Expected "\t" character, but found " " character  vue/html-indent

✖ 1 problem (1 error, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.
```

**Commentary**

This is roughly a re-opening of #321 .

> you should ... stick to one convention instead. 

This *is* sticking to one convention, the [SmartTabs](https://www.emacswiki.org/emacs/SmartTabs) convention, a convention [supported](https://eslint.org/docs/rules/no-mixed-spaces-and-tabs#smart-tabs) by ESLint proper. *"tabs for indentation, spaces for alignment"*

### PR DESCRIPTION
**Pull request by LukeShu**
This implements the feature requested in #426.  It's a little light on added tests.

The individual commit messages give a good description of the precise changes.

Besides implementing smart-tab, it makes a few changes in message formats:

 - Say "either X or Y spaces" if there are multiple indent levels that it would accept.
 - Say "Mixed spaces and tabs" if that's what the problem is
 - If a line's indentation fits a style, just not the prescribed style,
   say what the found indent was.  "Expected indentation of 1 tab but found
   2 spaces.", instead of the fairly opaque unexpected character message.
 - Have "0" be unitless.  Don't say "0 tabs" or "0 spaces".  Zero is 0.

Additionally, it will no longer offer to fix the indentation if there are multiple indent levels that it would accept.

### CODE REVIEW

**Comment by LukeShu** [comment]
@NaughtyMC

**Comment by LukeShu** [comment]
I just amended the wording of a comment.  There were no other changes.

**Comment by LukeShu** [comment]
Ping?

**Comment by ota-meshi** [comment]
This PR is so old that I will close it.

**Pull request closed without merging**
