### PR TITLE
⚙️Chore: Add warning about moving to scoped package

### PR DESCRIPTION
**Pull request by michalsnik**

### CODE REVIEW

**Comment by mysticatea** [comment]
CI failing seems to be caused by the new install script. Would you investigate it?

**Comment by mysticatea** [comment]
Also, installing looks failed:

```
C:\Users\starc\Documents\GitHub\sandbox> npm i github:vuejs/eslint-plugin-vue#add-warning-about-scoped-pkg

> eslint-plugin-vue@4.2.0 install C:\Users\starc\Documents\GitHub\sandbox\node_modules\eslint-plugin-vue
> node ./tools/warn-moved.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\starc\Documents\GitHub\sandbox\node_modules\eslint-plugin-vue\tools\warn-moved.js:1:
77)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by michalsnik** [comment]
I forgot to add `work in progress` badge :D Will finish it in the evening

**Comment by michalsnik** [comment]
I'm closing this PR. We'll come back to this once eslint supports scoped packages.

**Pull request closed without merging**
