### PR TITLE
feat: add new `v-bind-same-name-style` rule

### PR DESCRIPTION
**Pull request by waynzh**
close https://github.com/vuejs/eslint-plugin-vue/issues/2359.

Still figuring out how to categorize and set default value for this new rule. For now, I've set `never` as the default to avoid causing any breaking changes.

### CODE REVIEW

**Comment by ota-meshi** [comment]
Thank you for working on this change.
However, I would rather add new options to existing [vue/v-bind-style] rule than add new rule. What do you think?
(Sorry, I should have commented on this earlier.)

[vue/v-bind-style]: https://eslint.vuejs.org/rules/v-bind-style.html

**Comment by waynzh** [comment]
> I would rather add new options

Thanks for your input.

I've been contemplating whether to integrate this feature within the existing rule or to implement it as a separate one. I'm later leaning towards a separate rule as this rule particularly targets for cases where the `key` and `value` are the same name, one could use in `longform` and still omit the `value`.

Before next move, I'd like to gather opinions on the best way to incorporate this feature in [vue/v-bind-style](https://eslint.vuejs.org/rules/v-bind-style.html). Here are some options I'm considering:

1. Introduce a `sameNameShorthand` enum option that keeps the rule in shorthand form (e.g., `:foo=”bar”`) and omits the value only when it has same name `:foo="foo"` → `:foo` .
2. Modify the configuration to accept an array, allowing for combinations like `['longform', 'sameNameShorthand']`.
3. I'm open to other suggestions as well.

What do you think? I'm looking forward to your insights.

**Comment by ota-meshi** [comment]
My idea is to add a third object option.
This is probably what @FloEdelmann wrote in #2359.

```jsonc
{
   "vue/v-bind-style": [
     "error",
     "shorthand", // "shorthand", or "longform"
     {
       "sameNameShorthand": "ignore" // "always", "never", or "ignore"
     }
   ]
}
```

**Comment by waynzh** [comment]
Yeah, that makes sense to me. I'll close this PR for now, and when I find some time, I'll complete it and then open a new one.

**Pull request closed without merging**
