### PR TITLE
[Fix] Crash with babel-eslint

### LINKED ISSUE #213: Crash when loading 'vue/no-confusing-v-for-v-if'
**Tell us about your environment**

* **ESLint Version:** 4.7.2
* **eslint-plugin-vue Version:** 3.13.1
* **Node Version:** 8.5.0

**Please show your full configuration:**

```
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  env: {
    browser: true,
    es6: true,
    jest: true,
  },
  globals: {
    '$': true,
    '_': true,
    'google': true,
    // ...
  },
  // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
  extends: [
    'standard',
    'plugin:vue/recommended',
  ],
  // required to lint *.vue files
  plugins: [
    'html',
  ],
  // add your custom rules here
  rules: {
    'no-debugger': 'off',
    'comma-dangle': ['error', 'always-multiline'],
  }
}
```

Hard crash when loading rule.

**What actually happened? Please include the actual, raw output from ESLint.**

```
Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
TypeError: Error while loading rule 'vue/no-confusing-v-for-v-if': Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys.forEach.ruleId (/Users/guillaumechau/Documents/Projets/livestorm-container/livestorm-app/node_modules/eslint/lib/linter.js:934:24)
    at Array.forEach (<anonymous>)
    at Linter._verifyWithoutProcessors (/Users/guillaumechau/Documents/Projets/livestorm-container/livestorm-app/node_modules/eslint/lib/linter.js:871:35)
    at preprocess.map.textBlock (/Users/guillaumechau/Documents/Projets/livestorm-container/livestorm-app/node_modules/eslint/lib/linter.js:999:35)
    at Array.map (<anonymous>)
    at Linter.verify (/Users/guillaumechau/Documents/Projets/livestorm-container/livestorm-app/node_modules/eslint/lib/linter.js:998:42)
    at localVerify (/Users/guillaumechau/Documents/Projets/livestorm-container/livestorm-app/node_modules/eslint-plugin-html/src/index.js:107:14)
    at Linter.eslint.verify (/Users/guillaumechau/Documents/Projets/livestorm-container/livestorm-app/node_modules/eslint-plugin-html/src/index.js:147:18)
    at Linter.verifyAndFix (/Users/guillaumechau/Documents/Projets/livestorm-container/livestorm-app/node_modules/eslint/lib/linter.js:1080:29)
```

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #213.

It intended to show the message "Use the latest vue-eslint-parser", but it crashes.

This PR fixes the crash and adds tests to check that rules don't crash with `babel-eslint`.

### CODE REVIEW

**Comment by mysticatea** [comment]
Hmmm, it requires `eslint@4` because to use `require('eslint').Linter` API. Old API was deprecated. But `eslint-plugin-vue-libs` depends on too old ESLint. Can we change to another config? E.g. `standard`.

**Comment by michalsnik** [comment]
Thanks for fixing this! Maybe we can update https://github.com/vuejs/eslint-plugin-vue-libs ?

**Comment by mysticatea** [comment]
I upgraded `eslint-plugin-vue-libs` to 2.0.0.

**Comment by mysticatea** [comment]
I'm not sure why CircleCI job is failing. This project does not depend on `eslint-plugin-react`, but CurcleCI said it exists.

@michalsnik Could you rebuild the job without cache? I don't have the permission.

image

**Comment by mysticatea** [comment]
I fixed the test matter.

**Comment by michalsnik** [comment]
Thanks @mysticatea :) And sorry for not responding earlier..

**Pull request merged**
