### PR TITLE
Improve compatibility with ESLint v9

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR changes to not use APIs scheduled for removal in ESLint v9.

See https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/

### CODE REVIEW

**Comment by FloEdelmann** [comment]
Are the replacements available in all ESLint versions we support? See also https://github.com/vuejs/eslint-plugin-vue/issues/2166 where we can drop support for ESLint v7.

**Comment by ota-meshi** [comment]
Yes, I think we can support up to ESLint v6.2 for now.

**Review by FloEdelmann — APPROVED** [review]
Looks good to me then :slightly_smiling_face: 

One small (non-blocking) wish: Could you add a GitHub CI job with ESLint v9?

**Comment by ota-meshi** [comment]
Unfortunately, ESLint v9 has not even been released in alpha version yet :sweat:  We can add tests once it is released.

**Pull request merged**
