### PR TITLE
Add support for v-on="$listeners" (#89)

### LINKED ISSUE #89: Add support for v-on="$listeners"
The [no-invalid-v-on](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-invalid-v-on.md) rule is breaking for the new `v-on="$listeners"` feature in [Vue v2.4.0](https://github.com/vuejs/vue/releases/tag/v2.4.0)

**Tell us about your environment**

* **ESLint Version:** v3.19.0
* **eslint-plugin-vue Version:** v3.5.1
* **Node Version:** v7.9.0

**What did you do? Please include the actual source code causing the issue.**
```
<template>
	<div>
		<input v-on="$listeners">
	</div>
</template>
```

**What did you expect to happen?**
No warning/errors.

**What actually happened? Please include the actual, raw output from ESLint.**
```

WARNING in ./src/components/Input/src/Input.vue

  ✘  https://google.com/#q=vue%2Fno-invalid-v-on  'v-on' directives require event names
  src/components/Input/src/Input.vue:12:4
  			v-on="$listeners"
```

### PR DESCRIPTION
**Pull request by armano2**
this pull request fixes #89

### CODE REVIEW

**Comment by nickmessing** [comment]
Theoretically we could use something like:
```html
<template>
  <button v-on="listeners">Hey</button>
</template>
<script>
export default {
  data: () => ({ // doesn't have to be in data, just an example
    listeners: {
      click: someFn,
      keyup: someOtherFn
    }
  })
}
</script>
```

And it is valid in Vue starting with 2.4.0. This is a bad pattern most of the time but sometimes it could be useful like having a computed property that removes `click` from `$listeners` but has anything else.

Do we consider that?

**Comment by armano2** [comment]
Not in this PR, also for now Vue itself do not support this syntax (or maybe i understand this incorrectly)

**Comment by nickmessing** [comment]
@armano2, vue does support that so I am not sure this rule is valid anymore, here's an example: https://jsfiddle.net/z8y5fpx6/

**Comment by armano2** [comment]
thank you for clarification, part of this rule has been removed

**Pull request merged**
