### PR TITLE
refactor: remove eslint internal `traverser`

### PR DESCRIPTION
**Pull request by fisker**
eslin@6 has moved `traverser.js` to `lib/shared`

https://github.com/eslint/eslint/pull/11555

### CODE REVIEW

**Comment by fisker** [comment]
@mysticatea

**Comment by g-plane** [comment]
However, using internal code of ESLint isn't safe, and it can be changed even it semver-patch release.

**Comment by fisker** [comment]
@g-plane I understand the risk, any good idea?

**Comment by g-plane** [comment]
IMHO, using a third-party traverser package like `@babel/traverser` may be for workaround.

**Comment by Baune8D** [comment]
typescript-eslint has solved a similar problem in this issue: https://github.com/typescript-eslint/typescript-eslint/issues/563

They seem to have replaced the traverser with a custom implementation.

**Comment by mysticatea** [comment]
Thank you for your contribution.

I think `require("vue-eslint-parser").AST.traverse()` is better.

**Comment by yi-ge** [comment]
Thank you.

**Comment by fisker** [comment]
@mysticatea this is ready for review

**Pull request merged**
