### PR TITLE
feat(no-unused-properties): mark $props.<prop> as used

### LINKED ISSUE #2344: [no-unused-properties] can't recognize $props.xxx used
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.55.0
- **eslint-plugin-vue version:** 9.19.2
- **Node version:** not applied, repro in playground
- **Operating System:** not applied, repro in playground

**Please show your full configuration:**

```json5
{
    "rules": {
        'vue/no-unused-properties': 'error',
    }
}
```

**What did you do?**	

```vue
<template>
  <div :class="$props.class"></div>
  <div>{{$props.for}}</div>
</template>

<script lang="ts" setup>
defineProps<{
  class: string
  for: number
}>()
</script>
```

**What did you expect to happen?**

props: `class` and `for` not reported as unused

**What actually happened?**

props: `class` and `for` reported as unused

**Repository to reproduce this issue**

[playground link](https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJxNz8GKwyAQgOFXkWEPXWg20KO4YR9hHyCXNJkWwU5kZiwU8d2rTbrscfz1UzPM64JgwSneYpgUh5GMcYu/GzuHSeR7hI/Ia5Sv1zjC4Ppa/7YNOe/9snIp7+j6f2AdZWYf1YSJrlXU6hhBTbHWBS+e8LcZLjf2dZE1ouzp2haqbA2l2xl5pDIcPpu/ifU8HIFTQAGb4Z6wp7VLlASXrr0LWX1rp3KEOLEg19/+6CPiBnQowZP2eytPzVthxA==)

**Bug description:**

When we want to define a prop name as a js keyword (for example: class, for, ...) it is required to use them as `$props.PROP`, because using simply as `PROP` will lead to [parsing error](https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJxNjjEKwzAMRa9iNLWQYOho3NAj9ABeTKwGg+sYSw6UkLtXSTp0EtL7evwVxjkgGLCM75I84+CyUjbERZkxeaK7g2M6GKyWs3Cr/8Ky0lhjYZV8niTNElWE3IrQgK+Y8VnnQnbdzYfLKOIa8+TyNlyuu/BUyAN0UFtCArPC0lDnuW+5EYa+iAQrx53dtg6Kr4RVqj/4U/AU9EgpZtY/tn0BRZFPmg==).

Another option is to use as `props.PROP` with props variable declaration

```vue
<template>
  <div :class="props.class"></div>
  <div>{{props.for}}</div>
</template>

<script lang="ts" setup>
const props = defineProps<{
  class: string
  for: number
}>()
</script>
```

but the rule doesn't support it too #2193

### PR DESCRIPTION
**Pull request by levchak0910**
fixes #2344 

@FloEdelmann could you please mark my issue as open again?

### CODE REVIEW

**Review by FloEdelmann — APPROVED** [review]
Looks good to me, thanks for the contribution! :slightly_smiling_face:

**Review by ota-meshi — COMMENTED** [review]
Thank you! Sorry for the late review. The added source code looks good, but doesn't this PR add support for using `this.$props` in component methods?

**Comment by levchak0910** [comment]
Hi @ota-meshi, thanks for the review

Initially, I didn't want to support it in `<script>` because

1. I was afraid of the implementation's complexity 
2. On my personal opinion using `this.$props.<prop>` should be discouraged

but

- with the understanding that my PR is just a half-solution
- after I [searched](https://github.com/search?q="this.%24props"+language%3AVue&type=code&l=Vue) a bit on GitHub, I saw that many people use `$props.<prop>` in their code
- with some more courage and time

I jumped into the code again and luckily it was not as hard as I expected )

So now the rule support `$props.<prop>` in both template and script

**Review by ota-meshi — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
