### PR TITLE
Fix formatting README.md & no-template-key.md

### PR DESCRIPTION
**Pull request by armano2**
github com-vuejs-eslint-plugin-vue

### CODE REVIEW

**Comment by michalsnik** [comment]
Thanks for submitting this PR @armano2, but we use https://github.com/vuejs/eslint-plugin-vue/blob/master/tools/update-rules.js to generate table in readme. And this script uses description directly from rules' files, so you should change description messages in each rule and then execute: `npm run update` which will automatically update readme.

**Comment by armano2** [comment]
i fixed docs/rules/no-template-key.md :dancer:

**Comment by michalsnik** [comment]
Yeah, but you changed Readme too, and it will be overwritten in the next release so we should update rules descriptions instead, so those changes will be permanent.

**Comment by armano2** [comment]
ok i will change this

**Pull request closed without merging**
