### PR TITLE
Add ESLint 6 to peerDeps

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

**Comment by McInkay** [comment]
Any chance getting this merged? It's kinda getting in our way just now.

**Comment by kazupon** [comment]
Looks good to me. 

@mysticatea 
Do you have any concerns?

**Comment by xPaw** [comment]
https://github.com/mysticatea/vue-eslint-parser/pull/48 also needs to be merged to fully resolve the compatibility:

> warning " > eslint-plugin-vue@5.2.3" has incorrect peer dependency "eslint@^5.0.0".
warning "eslint-plugin-vue > vue-eslint-parser@5.0.0" has incorrect peer dependency "eslint@^5.0.0".

**Comment by Kocal** [comment]
Any chance to get a new release? Actually we can't update to ESLint v6 without this PR being released. :confused: 

Thanks! :smile:

**Comment by sanscheese** [comment]
This seems to have made it to v5.2.2 but not v5.2.3?

**Comment by edmorley** [comment]
> This seems to have made it to v5.2.2 but not v5.2.3?

Any news on this? :-)

**Pull request merged**
