### PR TITLE
Improve `vue/multi-word-component-names` rule docs

### PR DESCRIPTION
**Pull request by zjfresh**
Rule `vue/multi-word-component-names`

### CODE REVIEW

**Comment by 4tj** [comment]
I think this rule is not friendly, component naming good or bad should be **directly** decided by Vue? Enable by default and throw an Error. 

Please google how many developers it causes trouble

**Comment by FloEdelmann** [comment]
You are free to disable this rule. But it is the first recommendation in the Style Guide, so the rule makes sense: https://vuejs.org/style-guide/rules-essential.html#use-multi-word-component-names

**Comment by 4tj** [comment]
> You are free to disable this rule. But it is the first recommendation in the Style Guide, so the rule makes sense: https://vuejs.org/style-guide/rules-essential.html#use-multi-word-component-names

So why create a rule with the highest **disable rate** and enable it by default?

**Comment by FloEdelmann** [comment]
Because it is in the style guide and prevents errors. Note that you can also ignore single component names:

https://eslint.vuejs.org/rules/multi-word-component-names.html#options

**Comment by 4tj** [comment]
I know it can be disabled and just saying it's BAD design. 

At least it should just be a warning

**Comment by FloEdelmann** [comment]
That is something that can be discussed. Please open a new issue for that, with some evidence that this rule is really often disabled.

**Pull request merged**
