### PR TITLE
Upgrade vuepress and vue-eslint-editor.

### PR DESCRIPTION
**Pull request by ota-meshi**

### CODE REVIEW

**Comment by ota-meshi** [comment]
Hi @kazupon! I think it failed because of the netlify cache.
Can you clear the cache?

**Comment by kazupon** [comment]
@ota-meshi 
Done!

**Comment by ota-meshi** [comment]
@kazupon Thank you!

**Comment by ota-meshi** [comment]
@kazupon The same error is output on master. Can you please clear the cache again? :bow:
https://app.netlify.com/sites/eslint-plugin-vue/deploys

**Comment by kazupon** [comment]
@ota-meshi 
DONE!

**Comment by ota-meshi** [comment]
Thank you very much!

**Pull request merged**
