### PR TITLE
Breaking: support new syntax in Vue.js 2.6

### PR DESCRIPTION
**Pull request by mysticatea**
This PR updates `vue-eslint-parser` to 6.0.0, contains Vue.js 2.6 support.

> https://github.com/mysticatea/vue-eslint-parser/releases/tag/v6.0.0

This release contains drastic change about `VDirectiveKey` node to support dynamic argument syntax. Please see the release note.

This PR contains:

- [X] update package.json for `vue-eslint-parser@^6.0.0`.
- [X] update rules to pass tests.
- [X] add some tests about new syntax to check not to crash.

### CODE REVIEW

**Comment by ota-meshi** [comment]
For example, if you do the following test with `vue/array-bracket-spacing`, an error occurs because there is no space.

```js
    {
      code: '<template><div :[[attr]]="a" /></template>',
      options: ['always']
    }
```

Although this vue template is a useless, it seems to be valid as a template.

https://template-explorer.vuejs.org/#%3Cdiv%20%3A%5B%5Battr%5D%5D%3D%22a%22%20%2F%3E

I'd like to change the `wrapCoreRule` method to solve this issue as follows.

https://github.com/vuejs/eslint-plugin-vue/compare/vue-eslint-parser/6.0.0...vue-eslint-parser/6.0.0-wrap-core

What do you think?

**Comment by mysticatea** [comment]
Yeah, you are right. We must disable spacing rules in dynamic arguments. That `skipDynamicArguments` option is the same solution as I thought :smile:

Would you push it into this branch?

**Comment by ota-meshi** [comment]
@mysticatea Thank you for your comment.
I pushed this branch.

https://github.com/vuejs/eslint-plugin-vue/pull/807/commits/6037a9f9236110e6c7fd302e7d0f420a7741543e

I will change other wrapper rules later.

**Comment by ota-meshi** [comment]
I changed other wrapper rules as well.

https://github.com/vuejs/eslint-plugin-vue/pull/807/commits/00f6db9fb466046fa6b8c43aad2020ac9b082aa4

**Comment by mysticatea** [comment]
Awesome, thank you!

**Comment by mysticatea** [comment]
OK, I think done. Please review, @michalsnik, @ota-meshi, @armano2.

**Comment by mysticatea** [comment]
I'm sorry, please wait a bit. I found that I have overlooked about tests for references in dynamic arguments. (E.g. `vue/no-unused-vars`)

**Comment by mysticatea** [comment]
I believe done this time.

**Comment by mysticatea** [comment]
I'm considering if we should mark this PR as a breaking change.

This PR will not break CI for people which use our presets such as `vue/recommended`.
However, if someone uses `parser` setting with their version of `vue-eslint-parser`, this change will break it because AST was massively changed.

**Pull request merged**
