### PR TITLE
New: no-unused-vars (fixes #100).

### LINKED ISSUE #100: Rule Proposal: `vue/no-unused-vars`
## Please describe what the rule should do:

`no-unused-vars` should report variable definitions of `v-for` directives or `scope` attributes if those are not used.

## What category of rule is this? (place an "X" next to just one item)

[ ] Enforces code style
[X] Warns about a potential error
[ ] Suggests an alternate way of doing something
[ ] Other (please specify:)

## Provide 2-3 code examples that this rule will warn about:

```html
<template>
    <ol v-for="i in 5"><!-- "i" is defined but never used. -->
        <li>item</li>
    </ol>
</template>
<script>
export default {
}
</script>
```

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
fixes #100 

almost finished.:)

I'm not very familiar with the ASTs, so please let me know if missing something.

### CODE REVIEW

**Comment by armano2** [comment]
@Aladdin-ADD you are missing tests for nested interations & from what i understund you are doing alot recursive loops with `collectUsed`.

There is 2 fields witch can come in handy for this:
https://github.com/mysticatea/vue-eslint-parser/blob/master/docs/ast.md#vexpressioncontainer
-> `Reference`

**Comment by Aladdin-ADD** [comment]
SGTM. is there a way to get all properties and declarations? (seems it also need recurse)

**Comment by armano2** [comment]
@Aladdin-ADD 

```js
VElement (node) {
  if (node.variables) {
    for (const variable of node.variables) {
      variables.push(varNode)
    }
  }
},
```

**Comment by Aladdin-ADD** [comment]
I was a little confused. seems it didn't include the nested variables. eg.
```html
<template><div><ol scope="prop"></ol></div></template>
```
outside element `div`'s variables didn't include `prop`. 

let's be clear, we need to scan every inside elements(and inside), to check if it is used. (hope it can has a function in `ast-utils` to get all).

**Comment by armano2** [comment]
@Aladdin-ADD 
whats about:
```js
function create (context) {
  const stack = []
  let unused = []

  return utils.defineTemplateBodyVisitor(context, {
    'VElement:exit' () {
      unused
        .forEach((node) => {
          context.report({
            node,
            loc: node.loc,
            message: `'{{name}}' is defined but never used.`,
            data: {
              name: node.name
            }
          })
        })
      unused = stack.pop()
    },
    VElement (node) {
      stack.push(unused)
      unused = []
      if (node.variables) {
        for (const variable of node.variables) {
          unused.push(variable.id)
        }
      }
    },
    VExpressionContainer (node) {
      if (node.references) {
        for (const reference of node.references) {
          if (reference.mode !== 'w') {
            const name = reference.id.name
            unused = unused.filter((el) => el.name !== name)
            stack.forEach((list, i) => {
              stack[i] = list.filter((el) => el.name !== name)
            })
          }
        }
      }
    }
  })
}
```

btw. please merge code with master 🗡 there is nice update to parser there

**Comment by Aladdin-ADD** [comment]
great! and it looks better!

**Comment by armano2** [comment]
can you add few more tests ?

-> nested v-for and multiple scopes ?

**Comment by armano2** [comment]
and test for:
```
<template><ol v-for="i in data"><li v-for="f in i">{{ f.bar.baz }}</li></ol></template>
```

**Comment by mysticatea** [comment]
Thank you for contributing!

I'm sorry for late response.

I think we can simplify this rule.

```js
return utils.defineTemplateBodyVisitor(context, {
    VElement(node) {
        for (const variable of node.variables) {
            if (variable.references.length === 0) {
                context.report({
                    node: variable.id,
                    loc: variable.id.loc,
                    message: `'{{name}}' is defined but never used.`,
                    data: variable.id
                })
            }
        }
    }
})
```

**Comment by armano2** [comment]
@Aladdin-ADD we are missing one more test:

```vue
<template><div v-for="(v, i, c)"></div></template>
```
should warn about 3 unused variables

**Pull request merged**
