### PR TITLE
feat(v-bind-style): add `sameNameShorthand` option

### PR DESCRIPTION
**Pull request by waynzh**
close https://github.com/vuejs/eslint-plugin-vue/issues/2359.

This implementation follows https://github.com/vuejs/eslint-plugin-vue/issues/2359#issue-2072013209 and https://github.com/vuejs/eslint-plugin-vue/pull/2374#issuecomment-1913420004 of adding a `sameNameShorthand` option to the `v-bind-style` rule.

### CODE REVIEW

**Comment by waynzh** [comment]
Seems the tests are failing, but they all pass locally. Trying to figure out why 🤔

**Comment by ota-meshi** [comment]
Thank you for this PR!!!
The CI error seems to be a bug in the main branch. Don't worry about it now.

**Review by ota-meshi — APPROVED** [review]
LGTM!

**Review by FloEdelmann — CHANGES_REQUESTED** [review]

**Comment by FloEdelmann** [comment]
> Seems the tests are failing

They were fixed in #2382. You can pull the latest changes from `master` (with the "Update branch" button on GitHub) to fix the CI.

**Comment by waynzh** [comment]
Thanks for the review!

**Review by FloEdelmann — APPROVED** [review]

**Comment by FloEdelmann** [comment]
Thanks for applying the suggestions so quickly!

**Pull request merged**
